from __future__ import annotations

from pathlib import Path

from fastapi import HTTPException
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from sqlalchemy.orm import Session

from app.app_typing import UserLike
from app.core.config import get_settings
from app.models import Report
from app.repositories.user_repository import UserRepository
from app.services.academic_analysis import analyze_record
from app.services.academic_service import get_academic_record
from app.services.placement_service import get_placement_profile, placement_feature_snapshot, readiness_dimensions


def _output_path(user_id: str, report_type: str) -> Path:
    root = Path(get_settings().pdf_output_dir).resolve()
    root.mkdir(parents=True, exist_ok=True)
    return root / f"{report_type}-{user_id}.pdf"


def _build_pdf(path: Path, title: str, sections: list[tuple[str, list[str]]]) -> None:
    styles = getSampleStyleSheet()
    document = SimpleDocTemplate(str(path), pagesize=A4, title=title)
    story = [
        Paragraph("Gradient AI", styles["Title"]),
        Paragraph(title, styles["Heading2"]),
        Spacer(1, 12),
    ]
    for heading, lines in sections:
        story.append(Paragraph(heading, styles["Heading2"]))
        for line in lines:
            story.append(Paragraph(line, styles["BodyText"]))
        story.append(Spacer(1, 10))
    table = Table([["Generated by", "Gradient AI"], ["Report type", title]])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#17231f")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#d6ddd8")),
                ("PADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(table)
    document.build(story)


def create_academic_report(db: Session, user: UserLike, record_id: str) -> Report:
    profile = UserRepository(db).get_profile(user.id)
    record = get_academic_record(db, user.id, record_id)
    analysis = analyze_record(record)
    path = _output_path(user.id, "academic")
    sections = [
        ("Student Profile", [f"Name: {profile.full_name if profile else 'Student'}", f"Semester: {record.semester}"]),
        (
            "Academic History",
            [
                f"10th percentage: {record.tenth_percentage}",
                f"12th percentage: {record.twelfth_percentage}",
                f"Previous CGPA: {record.previous_cgpa}",
                f"Attendance: {record.attendance_percentage}%",
            ],
        ),
        (
            "IA Analysis",
            [
                f"Average IA percentage: {analysis['average_ia_percentage']}%",
                f"Weakest subject: {analysis['weakest_subject']}",
                f"Strongest subject: {analysis['strongest_subject']}",
            ],
        ),
        ("Recommendations", analysis["recommendations"]),
    ]
    _build_pdf(path, "Academic Intelligence Report", sections)
    report = Report(user_id=user.id, report_type="academic", title="Academic Intelligence Report", file_path=str(path))
    db.add(report)
    db.commit()
    db.refresh(report)
    return report


def create_placement_report(db: Session, user: UserLike) -> Report:
    profile = UserRepository(db).get_profile(user.id)
    placement = get_placement_profile(db, user.id)
    if placement is None:
        raise HTTPException(status_code=404, detail="Placement profile is required before generating a placement report")
    features = placement_feature_snapshot(db, user.id, placement)
    dimensions = readiness_dimensions(features)
    path = _output_path(user.id, "placement")
    sections = [
        ("Student Profile", [f"Name: {profile.full_name if profile else 'Student'}", f"Target role: {placement.target_role}"]),
        (
            "Placement Profile",
            [
                f"CGPA: {placement.cgpa}",
                f"Backlogs: {placement.backlog_count}",
                f"Aptitude: {placement.aptitude_score}%",
                f"Coding: {placement.coding_score}%",
                f"Communication: {placement.communication_score}%",
            ],
        ),
        ("Readiness Dimensions", [f"{key.title()}: {value}" for key, value in dimensions.items()]),
        (
            "Preparation",
            [
                f"Languages: {', '.join(placement.programming_languages) or 'Not added'}",
                f"Technical skills: {', '.join(placement.technical_skills) or 'Not added'}",
            ],
        ),
    ]
    _build_pdf(path, "Placement Intelligence Report", sections)
    report = Report(user_id=user.id, report_type="placement", title="Placement Intelligence Report", file_path=str(path))
    db.add(report)
    db.commit()
    db.refresh(report)
    return report


def get_report_for_user(db: Session, user_id: str, report_id: str) -> Report:
    report = db.query(Report).filter(Report.id == report_id, Report.user_id == user_id).first()
    if report is None:
        raise HTTPException(status_code=404, detail="Report not found")
    return report

